version: '3'

services:
  # ------------------------------------------------------------
  # ZOOKEEPER
  # ------------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    # CAMBIO: Nombre único para evitar conflicto
    container_name: zookeeper-strava
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  # ------------------------------------------------------------
  # KAFKA
  # ------------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    # CAMBIO: Nombre único
    container_name: kafka-strava
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      # CAMBIO: Apuntamos al nuevo nombre de zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-strava:2181
      
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      # CAMBIO: El listener interno ahora se anuncia como 'kafka-strava'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-strava:29092
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  # ------------------------------------------------------------
  # MINIO
  # ------------------------------------------------------------
  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    # CAMBIO: Nombre único
    container_name: minio-strava
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - kafka-net
    volumes:
      - minio_data:/data

  # ------------------------------------------------------------
  # INIT BUCKETS
  # ------------------------------------------------------------
  createbuckets:
    image: minio/mc
    # CAMBIO: Nombre único
    container_name: minio-init-strava
    depends_on:
      - minio
    networks:
      - kafka-net
    entrypoint: >
      /bin/sh -c "
      # CAMBIO: Conectamos a 'minio-strava' en lugar de 'minio'
      until (/usr/bin/mc config host add myminio http://minio-strava:9000 minioadmin minioadmin) do echo '...esperando a MinIO...'; sleep 5; done;
      /usr/bin/mc mb --ignore-existing myminio/strava-data;
      /usr/bin/mc policy set public myminio/strava-data;
      exit 0;
      "

networks:
  kafka-net:
    driver: bridge

volumes:
  minio_data: